name: Enforce Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title with Conventional Commits
        uses: ytanikin/pr-conventional-commits@1.4.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: 'true'
          custom_labels: '{"feat": "feature", "fix": "fix", "docs": "documentation", "test": "tests", "ci": "CI/CD", "refactor": "refactor", "perf": "performance", "chore": "chore", "revert": "revert"}'
          ticket_key_regex: ""

  validate-commits:
    name: Validate Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
