name: Dummy Status Check

on:
  pull_request:
    branches:
      - master

jobs:
  dummy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Always pass
        run: echo "Dummy status check passed!"
