name: Enforce Branching Rules

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  enforce-branching:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Check Base Branch
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" == "master" ]; then
            echo "❌ Pull requests must not target the 'master' branch."
            exit 1
          fi

      - name: Check Source Branch
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" == "master" ]; then
            echo "❌ Pull requests must not be submitted from 'master'. Use a feature branch instead."
            exit 1
          fi

      - name: Add Comment to PR
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            let message = "### 🚨 Pull Request Rejected\n\n"
            if ("${{ github.event.pull_request.base.ref }}" == "master") {
              message += "Pull requests **must not target the `master` branch**. Please update the base branch to `develop` or another valid branch.\n\n";
            }
            if ("${{ github.event.pull_request.head.ref }}" == "master") {
              message += "Pull requests **must not originate from the `master` branch** of your fork. Please create a feature branch and submit the pull request from there.\n\n";
            }
            message += "#### Steps to Fix:\n"
            message += "1. Close this pull request.\n";
            message += "2. Create a feature branch from `develop` on your fork:\n";
            message += "   ```bash\n   git checkout -b feature/your-feature develop\n   ```\n";
            message += "3. Commit your changes to the new feature branch.\n";
            message += "4. Push the branch to your fork:\n";
            message += "   ```bash\n   git push origin feature/your-feature\n   ```\n";
            message += "5. Open a new pull request targeting `develop`.\n\n";
            message += "For more details, see the [Contribution Guidelines](CONTRIBUTING.md).";

            github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })
