name: Enforce Branching Rules

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  enforce-branching:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      # Check if PR is targeting master
      - name: Check Base Branch
        id: check-base
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" == "master" ]; then
            echo "Pull requests must not target the 'master' branch." >> message.txt
            echo "base_error=true" >> $GITHUB_ENV
          else
            echo "base_error=false" >> $GITHUB_ENV
          fi

      # Check if PR is submitted from master
      - name: Check Source Branch
        id: check-source
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" == "master" ]; then
            echo "Pull requests must not originate from the 'master' branch." >> message.txt
            echo "source_error=true" >> $GITHUB_ENV
          else
            echo "source_error=false" >> $GITHUB_ENV
          fi

      # Add generic instructions
      - name: Add Fix Instructions
        run: |
          echo "#### Steps to Fix:" >> message.txt
          echo "1. Close this pull request." >> message.txt
          echo "2. Create a feature branch from \`develop\` on your fork:" >> message.txt
          echo "   \`\`\`bash" >> message.txt
          echo "   git checkout -b feature/your-feature develop" >> message.txt
          echo "   \`\`\`" >> message.txt
          echo "3. Commit your changes to the new feature branch." >> message.txt
          echo "4. Push the branch to your fork:" >> message.txt
          echo "   \`\`\`bash" >> message.txt
          echo "   git push origin feature/your-feature" >> message.txt
          echo "   \`\`\`" >> message.txt
          echo "5. Open a new pull request targeting \`develop\`." >> message.txt
          echo "" >> message.txt
          echo "For more details, see the [Contribution Guidelines](CONTRIBUTING.md)." >> message.txt

      # Add Comment to PR
      - name: Add Comment
        if: ${{ env.base_error == 'true' || env.source_error == 'true' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-path: message.txt

      # Fail Workflow
      - name: Fail Workflow
        if: ${{ env.base_error == 'true' || env.source_error == 'true' }}
        run: exit 1
